### PR TITLE
my take on courseflow

### PR DESCRIPTION
**Pull request by pdpinch**
Does it need screenshots?

### CODE REVIEW

**Comment by carsongee** [comment]
I'm pretty visual so I'd maybe like to see a flow chart of each of the workflows as a blow up of the overview page, but your call.  I think it is generally simple enough to just talk through as well.  I have screens of the course import and export screens in mine, so I don't know if screens are needed though maybe  a token screen of a sample multi author course PR would be a nice demo of the collab in case some of our audience aren't familiar with that feature

**Comment by pdpinch** [comment]
Good idea. I'll see if I can find a multi-author example to screenshot, and I'll think about blowing up the TMNT.

**Comment by pdpinch** [comment]
@carsongee now with 2 graphs and 2 screenshots.

**Comment by carsongee** [comment]
cool

**Pull request merged**
